name: PHP CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install tools
        run: composer install --no-interaction --no-progress
      - name: PHPCS
        run: composer lint
      - name: PHPStan
        run: composer stan
